import type { AttendeePath } from '../../../routes/attendee-route'
import { TicketIcon } from '../../../components/icons/TicketlyIcons'
import { formatTicketPrice } from '../../events'
import type { AttendeeOrder } from '../../orders'
import { ResaleCheckoutSteps } from '../components/ResaleCheckoutSteps'
import { getResaleListingById } from '../helpers/get-resale-listing-by-id'
import type { ResaleListing } from '../types/resale'
type Props = { listingId: string; listings: readonly ResaleListing[]; onNavigate: (path: AttendeePath) => void; order: AttendeeOrder | null }
export function ResaleResultPage({ listingId, listings, onNavigate, order }: Props) {
  const listing = getResaleListingById(listings, listingId)
  if (!listing || !order || order.source !== 'resale' || order.resaleListingId !== listingId) return <section className="px-6 py-24 text-center"><TicketIcon className="mx-auto h-12 w-12 text-coral" /><h1 className="mx-auto mt-5 max-w-[48rem] font-body text-5xl font-extrabold tracking-[-0.09em]">Chưa có giao dịch để hiển thị.</h1><p className="mx-auto mt-5 max-w-[38rem] text-ink-soft">Order mock chỉ tồn tại trong phiên hiện tại và phải khớp listing đã checkout.</p><button className="mt-7 min-h-12 rounded-md bg-blue px-5 font-extrabold text-paper" type="button" onClick={() => onNavigate('/resale')}>Quay lại chợ resale</button></section>
  const ticketId = order.issuedTicketIds[0]
  return <div className="px-6 py-[clamp(3.5rem,7vw,6.5rem)] mobile:px-5"><div className="mx-auto max-w-[68rem]"><ResaleCheckoutSteps current="complete" /><header className="mt-10 text-center"><p className="text-xs font-extrabold tracking-[0.12em] text-success">THANH TOÁN MOCK ĐÃ XÁC NHẬN</p><h1 className="mt-4 font-body text-[clamp(3.25rem,7vw,6.5rem)] leading-[0.79] font-extrabold tracking-[-0.105em]">Chỗ ngồi đã gọi tên bạn.</h1><p className="mx-auto mt-5 max-w-[42rem] leading-[1.7] text-ink-soft">Credential nguồn được mô phỏng là đã vô hiệu và vé mới đã phát hành trong phiên.</p></header><section className="mt-10 overflow-hidden rounded-lg border border-line bg-surface"><div className="bg-pine p-6 text-paper"><p className="text-xs font-extrabold tracking-[0.1em] text-mint">VÉ MỚI ĐÃ ĐƯỢC PHÁT HÀNH</p><h2 className="mt-3 font-body text-5xl font-extrabold tracking-[-0.09em]">{listing.eventTitle}</h2><p className="mt-4 text-story-copy">{listing.ticketType} · {listing.section}</p></div><dl className="grid grid-cols-2 gap-px bg-line mobile:grid-cols-1">{[['Mã giao dịch', order.id], ['Người nhận', order.buyer.fullName], ['Email nhận vé', order.buyer.email], ['Tổng thanh toán', formatTicketPrice(order.total)]].map(([label, value]) => <div key={label} className="bg-surface p-5"><dt className="text-xs font-extrabold text-ink-soft">{label.toUpperCase()}</dt><dd className="m-0 mt-2 break-words font-extrabold">{value}</dd></div>)}</dl></section><div className="mt-8 flex flex-wrap justify-center gap-3">{ticketId && <button className="min-h-12 rounded-md bg-coral px-5 font-extrabold text-paper" type="button" onClick={() => onNavigate(`/tickets/${ticketId}`)}>Mở e-ticket mới</button>}<button className="min-h-12 rounded-md border border-blue-deep/50 px-5 font-extrabold text-blue-deep" type="button" onClick={() => onNavigate('/orders')}>Xem đơn hàng</button><button className="min-h-12 rounded-md border border-blue-deep/50 px-5 font-extrabold text-blue-deep" type="button" onClick={() => onNavigate('/resale')}>Tiếp tục xem chợ</button></div></div></div>
}
