import { OrganizerEmptyState } from '../components/OrganizerEmptyState.tsx'
import { OrganizerEventCard } from '../components/OrganizerEventCard.tsx'
import { OrganizerEventTable } from '../components/OrganizerEventTable.tsx'
import { OrganizerPageHeader } from '../components/OrganizerPageHeader.tsx'
import { useOrganizerEventList } from '../hooks/use-organizer-event-list.ts'
import type { OrganizerEventStatus } from '../types/organizer-event.ts'
import type { OrganizerWorkspace } from '../types/organizer-workspace.ts'

type Props = { onCreate: () => void; onOpenEvent: (eventId: string) => void; workspace: OrganizerWorkspace; loading?: boolean; loadError?: string | null; onRetry?: () => void }
const statuses: readonly { label: string; value: OrganizerEventStatus | 'all' }[] = [{ label: 'Tất cả trạng thái', value: 'all' }, { label: 'Bản nháp', value: 'draft' }, { label: 'Chờ duyệt', value: 'pending_review' }, { label: 'Cần chỉnh sửa', value: 'changes_requested' }, { label: 'Đã duyệt', value: 'approved' }, { label: 'Đã xuất bản', value: 'published' }, { label: 'Đang diễn ra', value: 'ongoing' }, { label: 'Đã kết thúc', value: 'ended' }, { label: 'Đã hủy', value: 'cancelled' }, { label: 'Bị từ chối', value: 'rejected' }]
export function OrganizerEventListPage({ onCreate, onOpenEvent, workspace, loading = false, loadError = null, onRetry }: Props) {
  const list = useOrganizerEventList(workspace)
  // Server-backed states take precedence over the "no events" empty state so the page never
  // claims the organizer has no events while the real list is still loading or has failed.
  const body = loadError
    ? <OrganizerEmptyState title="Không tải được sự kiện" description={loadError} action={onRetry ? <button className="min-h-12 rounded-md border border-blue px-5 font-extrabold text-blue-deep" type="button" onClick={onRetry}>Thử lại</button> : undefined} />
    : loading
      ? <section className="rounded-lg border border-dashed border-line bg-surface p-8 text-center" role="status" aria-live="polite"><p className="m-0 font-bold text-ink-soft">Đang tải sự kiện của bạn…</p></section>
      : list.events.length
        ? <><div className="hidden md:block"><OrganizerEventTable events={list.events} onOpen={onOpenEvent} revenueFor={list.revenueFor} /></div><div className="grid gap-4 md:hidden">{list.events.map((event) => <OrganizerEventCard key={event.id} event={event} onOpen={onOpenEvent} revenue={list.revenueFor(event)} />)}</div></>
        : <OrganizerEmptyState title="Không tìm thấy sự kiện" description="Thử đổi từ khóa hoặc trạng thái lọc để xem lại danh sách." action={<button className="min-h-12 rounded-md border border-blue px-5 font-extrabold text-blue-deep" type="button" onClick={list.reset}>Xóa bộ lọc</button>} />
  return <div className="mx-auto max-w-7xl space-y-7"><OrganizerPageHeader eyebrow="QUẢN LÝ SỰ KIỆN" title="Sự kiện của tôi" actions={<button className="min-h-12 rounded-md bg-coral px-5 text-sm font-extrabold text-paper" type="button" onClick={onCreate}>+ Tạo sự kiện</button>}><p>Danh sách các sự kiện bạn đã tạo. Tìm nhanh theo tên, địa điểm hoặc tỉnh/thành phố; các bộ lọc chỉ áp dụng trong phiên hiện tại.</p></OrganizerPageHeader><section className="grid gap-3 rounded-lg border border-line bg-surface p-4 md:grid-cols-[minmax(0,1fr)_12rem_12rem]" aria-label="Bộ lọc sự kiện"><label className="text-sm font-bold" htmlFor="organizer-event-query">Tìm sự kiện<input id="organizer-event-query" className="mt-2 min-h-12 w-full rounded-md border border-line bg-paper px-3" value={list.filters.query} onChange={(event) => list.updateFilter('query', event.target.value)} placeholder="Tên, địa điểm, thành phố" /></label><label className="text-sm font-bold" htmlFor="organizer-event-status">Trạng thái<select id="organizer-event-status" className="mt-2 min-h-12 w-full rounded-md border border-line bg-paper px-3" value={list.filters.status} onChange={(event) => list.updateFilter('status', event.target.value as OrganizerEventStatus | 'all')}>{statuses.map((status) => <option key={status.value} value={status.value}>{status.label}</option>)}</select></label><label className="text-sm font-bold" htmlFor="organizer-event-sort">Sắp xếp<select id="organizer-event-sort" className="mt-2 min-h-12 w-full rounded-md border border-line bg-paper px-3" value={list.filters.sort} onChange={(event) => list.updateFilter('sort', event.target.value as typeof list.filters.sort)}><option value="date_asc">Ngày gần nhất</option><option value="date_desc">Ngày xa nhất</option><option value="revenue_desc">Doanh thu cao nhất</option></select></label></section>{body}</div>
}
