import { useState } from 'react'
import { OrganizerDashboardEventList } from '../components/OrganizerDashboardEventList.tsx'
import { OrganizerPageHeader } from '../components/OrganizerPageHeader.tsx'
import { selectOrganizerWorkspaceMetrics } from '../helpers/select-organizer-metrics.ts'
import type { OrganizerWorkspace } from '../types/organizer-workspace.ts'

import type { OrganizerEventStatus } from '../types/organizer-event.ts'

type Props = { onOpenEvent: (eventId: string) => void; onOpenEvents: () => void; workspace: OrganizerWorkspace }
const actionableStatuses: ReadonlySet<OrganizerEventStatus> = new Set(['draft', 'changes_requested', 'approved'])
function money(value: number) { return `${value.toLocaleString('vi-VN')}đ` }
export function OrganizerDashboardPage({ onOpenEvent, onOpenEvents, workspace }: Props) {
  const [currentTime] = useState(() => Date.now())
  const metrics = selectOrganizerWorkspaceMetrics(workspace)
  const upcoming = workspace.events.filter((event) => Date.parse(event.startsAt) >= currentTime).toSorted((a, b) => Date.parse(a.startsAt) - Date.parse(b.startsAt)).slice(0, 4)
  const actionable = workspace.events.filter((event) => actionableStatuses.has(event.status)).slice(0, 4)
  const recentActivity = workspace.checkInActivities.slice(0, 4).map((activity) => ({ activity, attendee: workspace.attendees.find((item) => item.id === activity.attendeeId), event: workspace.events.find((item) => item.id === activity.eventId) }))
  return <div className="mx-auto max-w-7xl space-y-7"><OrganizerPageHeader eyebrow="KHÔNG GIAN TỔ CHỨC" title="Chào mừng trở lại."><p>Quản lý sự kiện, theo dõi bán vé và xử lý các việc cần hoàn tất trong phiên minh họa.</p></OrganizerPageHeader><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Chỉ số tổng quan">{[['Doanh thu đã thanh toán', money(metrics.grossRevenue)], ['Vé đã bán', `${metrics.soldCount}/${metrics.capacity}`], ['Đơn hàng', String(metrics.orderCount)], ['Đã check-in', `${metrics.checkedInCount} (${Math.round(metrics.checkInRate * 100)}%)`]].map(([label, value]) => <article key={label} className="rounded-lg border border-line bg-surface p-5"><p className="m-0 text-sm font-bold text-ink-soft">{label}</p><strong className="mt-2 block text-3xl font-extrabold tracking-[-.06em] text-ink">{value}</strong></article>)}</section><div className="grid items-start gap-6 xl:grid-cols-2"><OrganizerDashboardEventList events={upcoming} onSelect={onOpenEvent} title="Sự kiện sắp tới" /><section className="rounded-lg border border-line bg-surface p-5"><div className="flex items-center justify-between gap-3"><h2 className="m-0 text-xl font-extrabold">Việc cần xử lý</h2><button className="min-h-11 text-sm font-extrabold text-blue-deep underline" type="button" onClick={onOpenEvents}>Xem tất cả</button></div><ul className="mt-4 space-y-3 p-0">{actionable.map((event) => <li key={event.id} className="rounded-md bg-paper-deep p-4"><button className="font-extrabold text-blue-deep underline-offset-4 hover:underline" type="button" onClick={() => onOpenEvent(event.id)}>{event.title}</button><p className="mt-1 mb-0 text-sm text-ink-soft">{event.status === 'draft' ? 'Hoàn thiện bản nháp và gửi duyệt.' : event.status === 'changes_requested' ? 'Admin yêu cầu chỉnh sửa trước khi gửi lại.' : 'Đã được duyệt, sẵn sàng xuất bản.'}</p></li>)}{actionable.length === 0 && <li className="text-sm text-ink-soft">Không có việc cần xử lý.</li>}</ul></section></div><section className="rounded-lg border border-line bg-surface p-5"><h2 className="m-0 text-xl font-extrabold">Hoạt động gần đây</h2><ul className="mt-4 divide-y divide-line p-0">{recentActivity.length ? recentActivity.map(({ activity, attendee, event }) => <li key={activity.id} className="py-3 text-sm"><strong>{attendee?.fullName ?? 'Khách tham dự'}</strong> đã check-in tại <button className="font-extrabold text-blue-deep underline" type="button" onClick={() => event && onOpenEvent(event.id)}>{event?.title ?? 'sự kiện'}</button>.</li>) : <li className="py-3 text-sm text-ink-soft">Chưa có hoạt động check-in.</li>}</ul></section></div>
}
