import { OrganizerEmptyState } from '../components/OrganizerEmptyState.tsx'
import { OrganizerEventNavigation } from '../components/OrganizerEventNavigation.tsx'
import { OrganizerEventReviewPanel } from '../components/OrganizerEventReviewPanel.tsx'
import { OrganizerPageHeader } from '../components/OrganizerPageHeader.tsx'
import { OrganizerStatusBadge } from '../components/OrganizerStatusBadge.tsx'
import { selectOrganizerEventMetrics } from '../helpers/select-organizer-metrics.ts'
import type { OrganizerPath, OrganizerRoute } from '../../../app/routing/organizer-route.ts'
import type { OrganizerWorkspace } from '../types/organizer-workspace.ts'

type Props = { activeRoute: OrganizerRoute; eventId: string; onNavigate: (path: OrganizerPath) => void; onPublish: (eventId: string) => void; onSubmitReview: (eventId: string) => void; workspace: OrganizerWorkspace }
const labels = { draft: 'Bản nháp', pending_review: 'Chờ duyệt', changes_requested: 'Cần chỉnh sửa', approved: 'Đã duyệt', published: 'Đã xuất bản', ongoing: 'Đang diễn ra', ended: 'Đã kết thúc', cancelled: 'Đã hủy', rejected: 'Bị từ chối' } as const
const tones = { draft: 'neutral', pending_review: 'blue', changes_requested: 'coral', approved: 'mint', published: 'mint', ongoing: 'blue', ended: 'neutral', cancelled: 'coral', rejected: 'coral' } as const
function date(value: string) { return new Intl.DateTimeFormat('vi-VN', { dateStyle: 'full', timeStyle: 'short' }).format(new Date(value)) }
export function OrganizerEventOverviewPage({ activeRoute, eventId, onNavigate, onPublish, onSubmitReview, workspace }: Props) {
  const event = workspace.events.find((item) => item.id === eventId)
  if (!event) return <OrganizerEmptyState title="Không tìm thấy sự kiện" description="Liên kết này không trỏ tới sự kiện nào trong phiên hiện tại." action={<button className="min-h-12 rounded-md bg-blue px-5 font-extrabold text-paper" type="button" onClick={() => onNavigate('/organizer/events')}>Về danh sách sự kiện</button>} />
  const metrics = selectOrganizerEventMetrics(workspace, eventId)
  return <div className="mx-auto max-w-7xl space-y-7"><OrganizerPageHeader eyebrow="TỔNG QUAN SỰ KIỆN" title={event.title} actions={<OrganizerStatusBadge label={labels[event.status]} tone={tones[event.status]} />}><p>{date(event.startsAt)} · {event.venue}, {event.city}</p></OrganizerPageHeader><OrganizerEventNavigation activeRoute={activeRoute} eventId={eventId} onNavigate={onNavigate} /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Doanh thu', `${metrics.grossRevenue.toLocaleString('vi-VN')}đ`], ['Đã bán', `${metrics.soldCount}/${metrics.capacity}`], ['Còn lại', String(metrics.remainingCount)], ['Check-in', `${metrics.checkedInCount} (${Math.round(metrics.checkInRate * 100)}%)`]].map(([label, value]) => <article key={label} className="rounded-lg border border-line bg-surface p-5"><p className="m-0 text-sm font-bold text-ink-soft">{label}</p><strong className="mt-2 block text-3xl font-extrabold tracking-[-.06em]">{value}</strong></article>)}</section><div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(20rem,.7fr)]"><section className="rounded-lg border border-line bg-surface p-5"><h2 className="m-0 text-xl font-extrabold">Bán vé và vận hành</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2"><div><dt className="font-bold text-ink-soft">Đơn hàng</dt><dd className="m-0 mt-1 text-2xl font-extrabold">{metrics.orderCount}</dd></div><div><dt className="font-bold text-ink-soft">Hạng vé</dt><dd className="m-0 mt-1 text-2xl font-extrabold">{metrics.ticketTiers.length}</dd></div></dl><p className="mt-5 text-sm leading-relaxed text-ink-soft">Danh sách vé, đơn hàng và người tham dự tiếp tục được quản lý ở các mục điều hướng của sự kiện.</p></section><OrganizerEventReviewPanel event={event} onPublish={onPublish} onSubmitReview={onSubmitReview} /></div></div>
}
