import { useMemo, useState } from 'react'
import { adminStatusLabel, adminStatusTone, formatAdminMoney } from '../helpers/admin-display.ts'
import { matchesAdminQuery } from '../helpers/filter-admin-records.ts'
import type { AdminSensitiveOperation } from '../helpers/admin-transitions.ts'
import type { AdminWorkspaceController } from '../hooks/admin-workspace-controller.ts'
import type { AdminPath } from '../../../app/routing/admin-route.ts'
import { shouldUseClientNavigation } from '../../../app/routing/client-navigation.ts'
import { AdminDataTable } from './AdminDataTable.tsx'
import { AdminDecisionDialog, AdminFilterToolbar, AdminPageHeader, AdminRecordDrawer, AdminStatusBadge } from './AdminCommon.tsx'

type Decision = { readonly title: string; readonly operation: AdminSensitiveOperation; readonly submit: (reason: string) => void }
type Choice = { readonly value: string; readonly label: string }
const statusChoices = (values: readonly string[]): readonly Choice[] => values.map((value) => ({ value, label: adminStatusLabel(value) }))
const refundStatusOptions = statusChoices(['requested', 'under_review', 'approved', 'rejected', 'completed'])
const payoutStatusOptions = statusChoices(['scheduled', 'pending', 'on_hold', 'released', 'paid'])

function adminAuditTargetPath(targetType: string, targetId: string): AdminPath | null {
  if (targetType === 'event') return `/admin/events/${encodeURIComponent(targetId)}/review`
  if (targetType === 'organizer') return '/admin/organizers'
  if (targetType === 'user') return '/admin/users'
  if (targetType === 'order') return '/admin/orders'
  if (targetType === 'ticket') return '/admin/tickets'
  if (targetType === 'resale') return '/admin/resale'
  if (targetType === 'refund') return '/admin/refunds'
  if (targetType === 'payout') return '/admin/payouts'
  if (targetType === 'category' || targetType === 'settings') return '/admin/settings'
  return null
}

function AdminSelect({ label, value, choices, onChange }: { readonly label: string; readonly value: string; readonly choices: readonly Choice[]; readonly onChange: (value: string) => void }) { return <label className="text-sm font-bold">{label}<select className="mt-1 min-h-11 w-full rounded border border-line bg-paper px-3" value={value} onChange={(event) => onChange(event.target.value)}>{choices.map((choice) => <option key={choice.value} value={choice.value}>{choice.label}</option>)}</select></label> }
function FinanceDecision({ decision, onClose }: { readonly decision: Decision | null; readonly onClose: () => void }) { return <AdminDecisionDialog open={Boolean(decision)} title={decision?.title ?? ''} description="Số tiền là readonly. Thao tác chỉ cập nhật trạng thái và audit trong phiên." confirmLabel="Xác nhận" operation={decision?.operation ?? 'approve_refund'} onCancel={onClose} onConfirm={(reason) => { decision?.submit(reason); onClose() }} /> }
function Status({ value }: { readonly value: string }) { return <AdminStatusBadge label={adminStatusLabel(value)} tone={adminStatusTone(value)} /> }
function Related({ title, items }: { readonly title: string; readonly items: readonly string[] }) { return <section><h3 className="m-0 text-base font-extrabold">{title}</h3>{items.length ? <ul className="mt-2 grid gap-1">{items.map((item) => <li key={item}>{item}</li>)}</ul> : <p className="mb-0 mt-2">Không có bản ghi liên quan trong fixture.</p>}</section> }

export function AdminRefundPage({ controller }: { readonly controller: AdminWorkspaceController }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [eventId, setEventId] = useState(''); const [organizerId, setOrganizerId] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null); const [decision, setDecision] = useState<Decision | null>(null)
  const refunds = useMemo(() => controller.workspace.refunds.filter((item) => (!status || item.status === status) && (!eventId || item.eventId === eventId) && (!organizerId || item.organizerId === organizerId) && matchesAdminQuery(query, [item.id, item.orderId, item.userId, item.reason])), [controller.workspace.refunds, eventId, organizerId, query, status])
  const selected = controller.workspace.refunds.find((item) => item.id === selectedId) ?? null
  return <div className="grid gap-6"><AdminPageHeader eyebrow="TÀI CHÍNH" title="Refund">Không chỉnh sửa số tiền và không gọi dịch vụ hoàn tiền thật.</AdminPageHeader><AdminFilterToolbar query={query} status={status} statusOptions={refundStatusOptions} resultCount={refunds.length} onQueryChange={setQuery} onStatusChange={setStatus} /><div className="grid gap-3 rounded-lg border border-line bg-surface p-4 sm:grid-cols-2"><AdminSelect label="Sự kiện" value={eventId} onChange={setEventId} choices={[{ value: '', label: 'Tất cả sự kiện' }, ...controller.workspace.events.map((item) => ({ value: item.id, label: item.title }))]} /><AdminSelect label="Organizer" value={organizerId} onChange={setOrganizerId} choices={[{ value: '', label: 'Tất cả Organizer' }, ...controller.workspace.organizers.map((item) => ({ value: item.id, label: item.name }))]} /></div><AdminDataTable label="Danh sách refund" headers={['Refund', 'Order', 'Buyer / event', 'Số tiền', 'Lý do', 'Ngày yêu cầu', 'Trạng thái']} rows={refunds.map((item) => ({ key: item.id, cells: [item.id, item.orderId, <span key="context">{controller.workspace.users.find((user) => user.id === item.userId)?.name ?? item.userId}<span className="block text-xs text-ink-soft">{controller.workspace.events.find((event) => event.id === item.eventId)?.title ?? item.eventId}</span></span>, formatAdminMoney(item.amount), item.reason, new Date(item.requestedAt).toLocaleString('vi-VN'), <Status key="status" value={item.status} />], onOpen: () => setSelectedId(item.id) }))} /><AdminRecordDrawer open={Boolean(selected)} title={selected?.id ?? ''} onClose={() => setSelectedId(null)}>{selected && <div className="grid gap-4 py-5"><p><strong>Số tiền readonly:</strong> {formatAdminMoney(selected.amount)}</p><p><strong>Order/payment:</strong> {selected.orderId} · {controller.workspace.orders.find((item) => item.id === selected.orderId)?.paymentStatus ?? 'Không còn khả dụng'}</p><Related title="Vụ việc liên quan" items={controller.workspace.cases.filter((item) => item.subjectType === 'refund' && item.subjectId === selected.id).map((item) => `${item.id} · ${item.summary}`)} />{['requested', 'under_review'].includes(selected.status) && <div className="flex flex-wrap gap-2"><button className="min-h-11 rounded bg-mint px-3 font-bold text-success" type="button" onClick={() => setDecision({ title: 'Duyệt refund', operation: 'approve_refund', submit: (reason) => controller.decideRefund(selected.id, 'approved', reason) })}>Duyệt</button><button className="min-h-11 rounded bg-error px-3 font-bold text-paper" type="button" onClick={() => setDecision({ title: 'Từ chối refund', operation: 'reject_refund', submit: (reason) => controller.decideRefund(selected.id, 'rejected', reason) })}>Từ chối</button></div>}</div>}</AdminRecordDrawer><FinanceDecision decision={decision} onClose={() => setDecision(null)} /></div>
}

export function AdminPayoutPage({ controller }: { readonly controller: AdminWorkspaceController }) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [organizerId, setOrganizerId] = useState(''); const [eventId, setEventId] = useState(''); const [caseOnly, setCaseOnly] = useState(''); const [selectedId, setSelectedId] = useState<string | null>(null); const [decision, setDecision] = useState<Decision | null>(null)
  const payouts = useMemo(() => controller.workspace.payouts.filter((item) => (!status || item.status === status) && (!organizerId || item.organizerId === organizerId) && (!eventId || item.eventId === eventId) && (!caseOnly || Boolean(item.caseId)) && matchesAdminQuery(query, [item.id, item.organizerId, item.eventId, item.caseId ?? ''])), [caseOnly, controller.workspace.payouts, eventId, organizerId, query, status])
  const selected = controller.workspace.payouts.find((item) => item.id === selectedId) ?? null
  return <div className="grid gap-6"><AdminPageHeader eyebrow="TÀI CHÍNH" title="Payout">Theo dõi trạng thái payout, không có CTA chuyển tiền.</AdminPageHeader><AdminFilterToolbar query={query} status={status} statusOptions={payoutStatusOptions} resultCount={payouts.length} onQueryChange={setQuery} onStatusChange={setStatus} /><div className="grid gap-3 rounded-lg border border-line bg-surface p-4 sm:grid-cols-2 xl:grid-cols-3"><AdminSelect label="Organizer" value={organizerId} onChange={setOrganizerId} choices={[{ value: '', label: 'Tất cả Organizer' }, ...controller.workspace.organizers.map((item) => ({ value: item.id, label: item.name }))]} /><AdminSelect label="Sự kiện" value={eventId} onChange={setEventId} choices={[{ value: '', label: 'Tất cả sự kiện' }, ...controller.workspace.events.map((item) => ({ value: item.id, label: item.title }))]} /><AdminSelect label="Có vụ việc" value={caseOnly} onChange={setCaseOnly} choices={[{ value: '', label: 'Tất cả payout' }, { value: 'yes', label: 'Có vụ việc' }]} /></div><AdminDataTable label="Danh sách payout" headers={['Payout', 'Organizer / event', 'Gross / refund / net', 'Lịch', 'Case', 'Trạng thái']} rows={payouts.map((item) => ({ key: item.id, cells: [item.id, <span key="context">{controller.workspace.organizers.find((organizer) => organizer.id === item.organizerId)?.name ?? item.organizerId}<span className="block text-xs text-ink-soft">{controller.workspace.events.find((event) => event.id === item.eventId)?.title ?? item.eventId}</span></span>, `${formatAdminMoney(item.grossAmount)} / ${formatAdminMoney(item.refundAmount)} / ${formatAdminMoney(item.netAmount)}`, new Date(item.scheduledAt).toLocaleDateString('vi-VN'), item.caseId ?? '—', <Status key="status" value={item.status} />], onOpen: () => setSelectedId(item.id) }))} /><AdminRecordDrawer open={Boolean(selected)} title={selected?.id ?? ''} onClose={() => setSelectedId(null)}>{selected && <div className="grid gap-4 py-5"><p>Gross: {formatAdminMoney(selected.grossAmount)} · Refund: {formatAdminMoney(selected.refundAmount)} · <strong>Net readonly: {formatAdminMoney(selected.netAmount)}</strong></p><Related title="Vụ việc liên quan" items={selected.caseId ? controller.workspace.cases.filter((item) => item.id === selected.caseId).map((item) => `${item.id} · ${item.summary}`) : []} />{selected.status !== 'paid' && <button className="min-h-11 w-fit rounded border border-coral px-3 font-bold text-coral-dark" type="button" onClick={() => setDecision(selected.status === 'on_hold' ? { title: 'Mở giữ payout', operation: 'release_payout', submit: (reason) => controller.setPayoutStatus(selected.id, 'released', reason) } : { title: 'Giữ payout', operation: 'hold_payout', submit: (reason) => controller.setPayoutStatus(selected.id, 'on_hold', reason) })}>{selected.status === 'on_hold' ? 'Mở giữ payout' : 'Giữ payout'}</button>}</div>}</AdminRecordDrawer><FinanceDecision decision={decision} onClose={() => setDecision(null)} /></div>
}

export function AdminSettingsPage({ controller }: { readonly controller: AdminWorkspaceController }) {
  const [label, setLabel] = useState('')
  const [checklist, setChecklist] = useState(() => [...controller.workspace.moderationChecklist])
  const [reasons, setReasons] = useState(() => [...controller.workspace.moderationReasons])
  const updateDraftItem = (items: readonly string[], index: number, value: string) => items.map((item, itemIndex) => itemIndex === index ? value : item)
  const saveSettings = () => {
    const nextChecklist = checklist.map((item) => item.trim())
    const nextReasons = reasons.map((item) => item.trim())
    const result = controller.updateModerationSettings(nextChecklist, nextReasons)
    if (result?.kind !== 'moderation_settings_updated') return
    setChecklist(nextChecklist)
    setReasons(nextReasons)
  }

  return <div className="grid gap-6"><AdminPageHeader eyebrow="HỆ THỐNG" title="Danh mục & cấu hình">Các cấu hình này chỉ tồn tại trong React session và reset khi tải lại.</AdminPageHeader><section className="rounded-lg border border-line bg-surface p-5"><h2 className="mt-0 text-xl font-extrabold">Danh mục sự kiện</h2><ul className="m-0 grid list-none gap-3 p-0">{controller.workspace.categories.map((item) => <li className="flex flex-wrap items-center justify-between gap-3 rounded border border-line p-3" key={item.id}><div><strong>{item.label}</strong><span className="ml-2 text-sm text-ink-soft">/{item.slug}</span></div><button className="min-h-11 rounded border border-blue px-3 font-bold text-blue-deep" type="button" onClick={() => controller.updateCategory(item.id, { label: item.label, active: !item.active })}>{item.active ? 'Tắt hiển thị' : 'Bật hiển thị'}</button></li>)}</ul><label className="mt-5 block text-sm font-bold">Đổi nhãn danh mục đầu tiên<input className="mt-1 min-h-11 w-full max-w-md rounded border border-line bg-paper px-3" value={label} onChange={(event) => setLabel(event.target.value)} /></label><button className="mt-2 min-h-11 rounded border border-blue px-3 font-bold text-blue-deep" type="button" onClick={() => { const first = controller.workspace.categories[0]; if (!first || !label.trim()) return; const result = controller.updateCategory(first.id, { label: label.trim(), active: first.active }); if (result?.kind === 'category_updated') setLabel('') }}>Lưu trong phiên</button></section><section className="grid gap-6 rounded-lg border border-line bg-surface p-5 lg:grid-cols-2"><div><h2 className="mt-0 text-xl font-extrabold">Checklist mặc định</h2>{checklist.map((item, index) => <label className="mt-3 block text-sm font-bold" key={index}>Mục {index + 1}<input className="mt-1 min-h-11 w-full rounded border border-line bg-paper px-3" value={item} onChange={(event) => setChecklist(updateDraftItem(checklist, index, event.target.value))} /></label>)}</div><div><h2 className="mt-0 text-xl font-extrabold">Lý do moderation gợi ý</h2>{reasons.map((item, index) => <label className="mt-3 block text-sm font-bold" key={index}>Lý do {index + 1}<input className="mt-1 min-h-11 w-full rounded border border-line bg-paper px-3" value={item} onChange={(event) => setReasons(updateDraftItem(reasons, index, event.target.value))} /></label>)}</div><div className="lg:col-span-2"><button className="min-h-11 rounded bg-pine px-4 font-extrabold text-paper" type="button" onClick={saveSettings}>Lưu cấu hình moderation</button></div></section></div>
}

export function AdminAuditLogPage({ controller, navigate }: { readonly controller: AdminWorkspaceController; readonly navigate: (path: AdminPath) => void }) {
  const [query, setQuery] = useState(''); const [action, setAction] = useState(''); const [targetType, setTargetType] = useState(''); const [actor, setActor] = useState(''); const [date, setDate] = useState('')
  const actions = [...new Set(controller.workspace.auditEntries.map((item) => item.action))]; const actors = [...new Set(controller.workspace.auditEntries.map((item) => item.actorLabel))]
  const entries = controller.workspace.auditEntries.filter((item) => (!action || item.action === action) && (!targetType || item.targetType === targetType) && (!actor || item.actorLabel === actor) && (!date || item.occurredAt.startsWith(date)) && matchesAdminQuery(query, [item.action, item.actorLabel, item.targetType, item.targetId, item.reason ?? '']))
  return <div className="grid gap-6"><AdminPageHeader eyebrow="HỆ THỐNG" title="Nhật ký quản trị">Nhật ký append-only, mới nhất ở trên cùng và chỉ đọc.</AdminPageHeader><label className="max-w-lg text-sm font-bold">Tìm kiếm nhật ký<input className="mt-1 min-h-11 w-full rounded border border-line bg-paper px-3" value={query} onChange={(event) => setQuery(event.target.value)} /></label><div className="grid gap-3 rounded-lg border border-line bg-surface p-4 sm:grid-cols-2 xl:grid-cols-4"><AdminSelect label="Hành động" value={action} onChange={setAction} choices={[{ value: '', label: 'Tất cả hành động' }, ...actions.map((value) => ({ value, label: value }))]} /><AdminSelect label="Loại đối tượng" value={targetType} onChange={setTargetType} choices={[{ value: '', label: 'Tất cả đối tượng' }, ...['event', 'organizer', 'user', 'order', 'ticket', 'resale', 'refund', 'payout', 'category', 'settings'].map((value) => ({ value, label: value }))]} /><AdminSelect label="Admin" value={actor} onChange={setActor} choices={[{ value: '', label: 'Tất cả Admin' }, ...actors.map((value) => ({ value, label: value }))]} /><label className="text-sm font-bold">Ngày<input className="mt-1 min-h-11 w-full rounded border border-line bg-paper px-3" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label></div><AdminDataTable label="Nhật ký quản trị" headers={['Thời điểm', 'Admin', 'Hành động', 'Đối tượng', 'Lý do']} rows={entries.map((item) => { const targetPath = adminAuditTargetPath(item.targetType, item.targetId); return { key: item.id, cells: [new Date(item.occurredAt).toLocaleString('vi-VN'), item.actorLabel, item.action, targetPath ? <a key="target" className="font-bold text-blue-deep underline" href={targetPath} onClick={(event) => { if (!shouldUseClientNavigation(event)) return; event.preventDefault(); navigate(targetPath) }}>{item.targetType} · {item.targetId}</a> : `${item.targetType} · ${item.targetId}`, item.reason ?? '—'] } })} /></div>
}
