import { useEffect, useRef, useState } from 'react'
import { OrganizerImagePicker } from './OrganizerImagePicker.tsx'
import { validateOrganizerTicketTier, type OrganizerTicketTierDraft } from '../helpers/validate-organizer-ticket-tier.ts'

type Props = { open: boolean; tier: OrganizerTicketTierDraft | null; onClose: () => void; onSave: (tier: OrganizerTicketTierDraft) => void; returnFocus: HTMLElement | null; startsAt: string; endsAt: string }
type Fields = { name: string; price: string; capacity: string; minPerOrder: string; perOrderLimit: string; salesStartAt: string; salesEndAt: string; description: string; image: string }
const empty = (startsAt: string, endsAt: string): Fields => ({ name: '', price: '0', capacity: '1', minPerOrder: '1', perOrderLimit: '4', salesStartAt: startsAt, salesEndAt: endsAt, description: '', image: '' })
function toFields(tier: OrganizerTicketTierDraft | null, startsAt: string, endsAt: string): Fields { return tier ? { name: tier.name, price: String(tier.price), capacity: String(tier.capacity), minPerOrder: String(tier.minPerOrder ?? 1), perOrderLimit: String(tier.perOrderLimit), salesStartAt: tier.salesStartAt, salesEndAt: tier.salesEndAt, description: tier.description ?? '', image: tier.image ?? '' } : empty(startsAt, endsAt) }

export function OrganizerEventTierDialog({ open, tier, onClose, onSave, returnFocus, startsAt, endsAt }: Props) {
  const [fields, setFields] = useState(() => toFields(tier, startsAt, endsAt)); const [message, setMessage] = useState(''); const closeRef = useRef<HTMLButtonElement>(null)
  useEffect(() => { if (!open) return; const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose() }; window.addEventListener('keydown', onKey); return () => { window.removeEventListener('keydown', onKey) } }, [open, onClose])
  useEffect(() => { if (open) closeRef.current?.focus(); else returnFocus?.focus() }, [open, returnFocus])
  if (!open) return null
  const update = (name: keyof Fields, value: string) => setFields((current) => ({ ...current, [name]: value }))
  const save = () => { const draft: OrganizerTicketTierDraft = { name: fields.name, price: Number(fields.price), capacity: Number(fields.capacity), minPerOrder: Number(fields.minPerOrder), perOrderLimit: Number(fields.perOrderLimit), salesStartAt: fields.salesStartAt, salesEndAt: fields.salesEndAt, description: fields.description, ...(fields.image ? { image: fields.image } : {}) }; const result = validateOrganizerTicketTier(draft); if (!result.valid) { setMessage(Object.values(result.errors)[0] ?? 'Kiểm tra lại loại vé.'); return }; onSave(draft); onClose() }
  const inputs = [['name', 'Tên vé', 'text'], ['price', 'Giá (0 = miễn phí)', 'number'], ['capacity', 'Tổng số lượng', 'number'], ['minPerOrder', 'Tối thiểu mỗi đơn', 'number'], ['perOrderLimit', 'Tối đa mỗi đơn', 'number'], ['salesStartAt', 'Mở bán', 'datetime-local'], ['salesEndAt', 'Kết thúc bán', 'datetime-local']] as const
  return <div className="fixed inset-0 z-50 grid place-items-center bg-pine/70 p-4" role="presentation"><section className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-lg bg-paper p-5 shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="organizer-tier-dialog-title"><div className="flex items-start justify-between gap-4"><h2 id="organizer-tier-dialog-title" className="text-2xl font-extrabold">{tier ? 'Chỉnh sửa loại vé' : 'Tạo loại vé'}</h2><button ref={closeRef} type="button" className="min-h-10 rounded-md border border-line px-3 font-bold" onClick={onClose}>Hủy</button></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{inputs.map(([name, label, type]) => <label key={name} className="text-sm font-bold">{label}<input className="mt-2 min-h-11 w-full rounded-md border border-line bg-surface px-3" type={type} min={type === 'number' ? 0 : undefined} value={fields[name]} onChange={(event) => update(name, event.target.value)} /></label>)}</div><label className="mt-4 block text-sm font-bold">Mô tả vé<textarea className="mt-2 min-h-24 w-full rounded-md border border-line bg-surface p-3" value={fields.description} onChange={(event) => update('description', event.target.value)} /></label><OrganizerImagePicker label="Ảnh vé" value={fields.image} onChange={(value) => update('image', value)} maxMb={1} />{message && <p className="mt-3 text-sm font-bold text-error" role="alert">{message}</p>}<button type="button" className="mt-5 min-h-11 rounded-md bg-blue px-5 font-extrabold text-paper" onClick={save}>Lưu loại vé</button></section></div>
}
