import type { AttendeePath } from '../../../app/routing/attendee-route'
import { formatTicketPrice } from '../../events'
import type { AttendeeOrder } from '../types/order'
import { OrderDetailTimeline } from '../components/OrderDetailTimeline'
import { OrderStatusBadge } from '../components/OrderStatusBadge'
type Props = { orderId: string; orders: readonly AttendeeOrder[]; onNavigate: (path: AttendeePath) => void }
export function OrderDetailPage({ orderId, orders, onNavigate }: Props) {
  const order = orders.find((candidate) => candidate.id === orderId)
  if (!order) return <section className="px-6 py-24 text-center"><h1 className="font-body text-5xl font-extrabold">Không tìm thấy đơn hàng.</h1><button className="mt-6 min-h-12 rounded-md bg-blue px-5 font-extrabold text-paper" type="button" onClick={() => onNavigate('/orders')}>Quay lại đơn hàng</button></section>
  return <div className="px-6 py-[clamp(3.5rem,7vw,6rem)] mobile:px-5"><div className="mx-auto max-w-[68rem]"><button className="min-h-11 font-extrabold text-blue-deep" type="button" onClick={() => onNavigate('/orders')}>← Tất cả đơn hàng</button><header className="mt-6 rounded-lg bg-pine p-6 text-paper"><OrderStatusBadge status={order.status} /><p className="mt-4 text-xs font-extrabold tracking-[0.1em] text-mint">{order.source === 'primary' ? 'VÉ CHÍNH THỨC' : 'GIAO DỊCH RESALE'} · {order.id}</p><h1 className="mt-3 font-body text-[clamp(2.7rem,6vw,5rem)] leading-[0.84] font-extrabold tracking-[-0.095em]">{order.eventTitle}</h1></header><section className="mt-7 rounded-lg border border-line bg-surface p-6"><h2 className="m-0 text-2xl font-extrabold">Chi tiết thanh toán</h2><dl className="mt-5 grid grid-cols-2 gap-5 mobile:grid-cols-1"><div><dt className="text-sm text-ink-soft">Người mua</dt><dd className="m-0 mt-1 font-bold">{order.buyer.fullName}<br />{order.buyer.email}<br />{order.buyer.phone}</dd></div><div><dt className="text-sm text-ink-soft">Thời gian tạo</dt><dd className="m-0 mt-1 font-bold">{new Date(order.createdAt).toLocaleString('vi-VN')}</dd></div></dl><div className="mt-6 border-t border-line pt-5">{order.items.map((item) => <div key={item.label} className="flex justify-between gap-4"><span>{item.label} × {item.quantity}</span><strong>{formatTicketPrice(item.unitPrice * item.quantity)}</strong></div>)}<div className="mt-4 flex justify-between border-t border-line pt-4 text-xl"><span>Tổng thanh toán</span><strong className="text-blue-deep">{formatTicketPrice(order.total)}</strong></div></div></section><OrderDetailTimeline status={order.status} /><div className="mt-7 flex flex-wrap gap-3">{order.issuedTicketIds.map((ticketId, index) => <button key={ticketId} className="min-h-12 rounded-md bg-coral px-5 font-extrabold text-paper" type="button" onClick={() => onNavigate(`/tickets/${ticketId}`)}>Mở vé {index + 1}</button>)}{order.status !== 'completed' && <button className="min-h-12 rounded-md border border-blue-deep/50 px-5 font-extrabold text-blue-deep" type="button" onClick={() => onNavigate(order.source === 'primary' ? `/events/${order.eventId}` : '/resale')}>Quay lại lựa chọn</button>}</div></div></div>
}
