import type { AttendeePath } from '../../../routes/attendee-route'
import type { AttendeeOrder } from '../../orders'
import { formatTicketPrice } from '../../events'
import { PrimaryCheckoutSteps } from '../components/PrimaryCheckoutSteps'
type Props = { eventId: string; order: AttendeeOrder | null; onNavigate: (path: AttendeePath) => void }
const copy = {
  completed: ['THANH TOÁN DEMO THÀNH CÔNG', 'Vé đã sẵn sàng trong ví của bạn.', 'Order mock đã hoàn tất và credential demo được phát hành.'],
  failed: ['THANH TOÁN DEMO THẤT BẠI', 'Giao dịch chưa thể hoàn tất.', 'Không có vé nào được phát hành. Bạn có thể quay lại checkout và thử trạng thái khác.'],
  expired: ['PHIÊN GIỮ CHỖ ĐÃ HẾT HẠN', 'Lựa chọn đã được trả về sự kiện.', 'Prototype không giữ tồn vé. Hãy quay lại sự kiện để chọn lại.'],
} as const
export function PrimaryOrderResultPage({ eventId, order, onNavigate }: Props) {
  if (!order || order.eventId !== eventId || order.source !== 'primary') return <section className="px-6 py-24 text-center"><h1 className="font-body text-5xl font-extrabold">Chưa có kết quả thanh toán.</h1><p className="mt-4 text-ink-soft">Kết quả chỉ tồn tại trong phiên sau khi hoàn tất checkout.</p><button className="mt-6 min-h-12 rounded-md bg-blue px-5 font-extrabold text-paper" type="button" onClick={() => onNavigate(`/events/${eventId}`)}>Quay lại sự kiện</button></section>
  const [eyebrow, title, detail] = copy[order.status]
  const firstTicket = order.issuedTicketIds[0]
  return <div className="px-6 py-[clamp(3.5rem,7vw,6rem)] mobile:px-5"><div className="mx-auto max-w-[68rem]"><PrimaryCheckoutSteps current="complete" /><header className="mt-10 text-center"><p className={`text-xs font-extrabold tracking-[0.12em] ${order.status === 'completed' ? 'text-success' : 'text-coral-dark'}`}>{eyebrow}</p><h1 className="mx-auto mt-4 max-w-[56rem] font-body text-[clamp(3rem,7vw,6rem)] leading-[0.82] font-extrabold tracking-[-0.1em]">{title}</h1><p className="mx-auto mt-5 max-w-[42rem] leading-[1.7] text-ink-soft">{detail}</p></header><section className="mx-auto mt-9 max-w-[48rem] rounded-lg border border-line bg-surface p-6"><dl className="grid grid-cols-2 gap-5 mobile:grid-cols-1"><div><dt className="text-sm text-ink-soft">Mã đơn</dt><dd className="m-0 mt-1 font-extrabold">{order.id}</dd></div><div><dt className="text-sm text-ink-soft">Trạng thái</dt><dd className="m-0 mt-1 font-extrabold">{order.status === 'completed' ? 'Đã thanh toán' : order.status === 'failed' ? 'Thất bại' : 'Hết hạn'}</dd></div><div><dt className="text-sm text-ink-soft">Sự kiện</dt><dd className="m-0 mt-1 font-extrabold">{order.eventTitle}</dd></div><div><dt className="text-sm text-ink-soft">Tổng tiền</dt><dd className="m-0 mt-1 font-extrabold text-blue-deep">{formatTicketPrice(order.total)}</dd></div></dl></section><div className="mt-8 flex flex-wrap justify-center gap-3">{firstTicket && <button className="min-h-12 rounded-md bg-coral px-5 font-extrabold text-paper" type="button" onClick={() => onNavigate(`/tickets/${firstTicket}`)}>Mở e-ticket</button>}{order.status === 'failed' && <button className="min-h-12 rounded-md bg-coral px-5 font-extrabold text-paper" type="button" onClick={() => onNavigate(`/events/${eventId}/checkout`)}>Thử lại checkout</button>}<button className="min-h-12 rounded-md border border-blue-deep/50 bg-surface px-5 font-extrabold text-blue-deep" type="button" onClick={() => onNavigate(order.status === 'expired' ? `/events/${eventId}` : '/orders')}>{order.status === 'expired' ? 'Chọn lại vé' : 'Xem đơn hàng'}</button></div></div></div>
}
